name: 'Lint and Syntax Check'
description: 'Runs lint and syntax check tests on each file of the repo'
inputs: {}
runs:
  using: 'composite'
  steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install yamllint
      run: pip install yamllint
      shell: bash

    - name: Run yamllint
      run: |
        yamllint .
      shell: bash

    - name: Install ShellCheck
      run: sudo apt-get install -y shellcheck
      shell: bash

    - name: Run ShellCheck
      run: |
        find . -name "*.sh" -exec shellcheck {} \;
      shell: bash

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install ESLint
      run: npm install -g eslint
      shell: bash

    - name: Run ESLint
      run: |
        eslint '**/*.js'
      shell: bash

    - name: Install pylint
      run: pip install pylint
      shell: bash

    - name: Run pylint
      run: |
        find . -name "*.py" -exec pylint {} \;
      shell: bash
